/**
 * experience/cluster — Failure clustering and insight extraction.
 *
 * Reads from the ExperienceStore and groups failures by common patterns
 * to surface the top pain points. This turns raw session data into
 * an actionable product roadmap.
 */

import { experienceStore, type ClusterInsight } from "./store"
import { createLogger } from "../cli/logger"

const log = createLogger("experience:cluster")

export interface ClusterReport {
  generatedAt: string
  totalExperiences: number
  failureRate: number
  topClusters: ClusterInsight[]
  skillCandidates: Array<{ name: string; confidence: number; steps: string[]; goal: string }>
  stats: {
    totalExperiences: number
    successCount: number
    failureCount: number
    avgReward: number
  }
}

/**
 * Generate a full cluster analysis report.
 * This is the main entry point for the self-analysis cron job.
 */
export function generateClusterReport(minClusterSize = 2): ClusterReport {
  const stats = experienceStore.getStats()
  const clusters = experienceStore.computeClusterInsights(minClusterSize)
  const skillCandidates = experienceStore.findSkillCandidates(3)
  const total = stats.totalExperiences || 1

  return {
    generatedAt: new Date().toISOString(),
    totalExperiences: stats.totalExperiences,
    failureRate: Math.round((stats.failureCount / total) * 100),
    topClusters: clusters.slice(0, 5),
    skillCandidates: skillCandidates.slice(0, 10),
    stats: {
      totalExperiences: stats.totalExperiences,
      successCount: stats.successCount,
      failureCount: stats.failureCount,
      avgReward: Math.round(stats.avgReward * 100) / 100,
    },
  }
}

/**
 * Format a cluster report as a human-readable markdown string.
 * Suitable for console output or Telegram message.
 */
export function formatClusterReport(report: ClusterReport): string {
  const lines: string[] = []

  lines.push("## 📊 Experience Cluster Report")
  lines.push("")
  lines.push(`**Generated:** ${report.generatedAt}`)
  lines.push(`**Total Experiences:** ${report.totalExperiences}`)
  lines.push(`**Failure Rate:** ${report.failureRate}%`)
  lines.push(`**Avg Reward:** ${report.stats.avgReward}`)
  lines.push("")

  if (report.topClusters.length === 0) {
    lines.push("✅ No significant failure clusters detected.")
    lines.push("")
  } else {
    lines.push("### 🔴 Top Failure Clusters")
    lines.push("")
    for (const cluster of report.topClusters) {
      lines.push(`**Cluster ${cluster.id}:** "${cluster.clusterKey}" — ${cluster.count} occurrence(s)`)
      lines.push("")
      if (cluster.commonFailures.length > 0) {
        lines.push("Common patterns:")
        for (const f of cluster.commonFailures) {
          lines.push(`  - \`${f.pattern}\` × ${f.count}`)
        }
        lines.push("")
      }
      lines.push("Suggestions:")
      for (const s of cluster.topSuggestions) {
        lines.push(`  → ${s}`)
      }
      lines.push("")
    }
  }

  if (report.skillCandidates.length > 0) {
    lines.push("### 🧠 Skill Candidates (from successful runs)")
    lines.push("")
    for (const sc of report.skillCandidates) {
      lines.push(`- **${sc.name}** — ${sc.confidence}% confidence`)
      lines.push(`  Steps: ${sc.steps.join(" → ")}`)
      lines.push(`  Goal: "${sc.goal.slice(0, 80)}"`)
      lines.push("")
    }
  }

  lines.push("---")
  lines.push(`*Report generated by experience cluster analyzer*`)

  return lines.join("\n")
}

/**
 * Update MEMORY.md with the latest cluster insights.
 * Called by the daily cron job to keep the project's memory fresh.
 */
export async function writeInsightsToMemory(): Promise<void> {
  const report = generateClusterReport()

  if (report.topClusters.length === 0 && report.skillCandidates.length === 0) return

  const { memorySystem } = await import("../memory/system")

  const section = [
    "## Experience Cluster Analysis",
    "",
    `**Date:** ${report.generatedAt}`,
    `**Total experiences:** ${report.totalExperiences}`,
    `**Failure rate:** ${report.failureRate}%`,
    "",
    ...report.topClusters.map(
      (c) => `- 🔴 \`${c.clusterKey}\` — ${c.count} occurrence(s)`,
    ),
    ...report.skillCandidates.map(
      (c) => `- 🧠 \`${c.name}\` — ${c.confidence}% confidence`,
    ),
    "",
  ].join("\n")

  await memorySystem.appendToMemory(section)
  log.info("Wrote cluster insights to MEMORY.md")
}
